<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="QZ-LT-R-CTK-023" failures="1" tests="2" name="Code5HashMapToDataProviderToSendTheDataAsOneHashObject" time="153.154" errors="0" timestamp="20 Nov 2024 07:33:27 GMT">
  <testcase classname="End_To_End_SeleniumFramework.Code5HashMapToDataProviderToSendTheDataAsOneHashObject" name="submitOrder" time="20.635">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at End_To_End_SeleniumFramework.Code5HashMapToDataProviderToSendTheDataAsOneHashObject.submitOrder(Code5HashMapToDataProviderToSendTheDataAsOneHashObject.java:31)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- submitOrder -->
  <testcase classname="End_To_End_SeleniumFramework.Code5HashMapToDataProviderToSendTheDataAsOneHashObject" name="submitOrder" time="10.804"/>
  <testcase classname="End_To_End_SeleniumFramework.Code5HashMapToDataProviderToSendTheDataAsOneHashObject" name="OrderHistory" time="0.0">
    <ignored/>
  </testcase> <!-- OrderHistory -->
</testsuite> <!-- Code5HashMapToDataProviderToSendTheDataAsOneHashObject -->
